---
title: "Heterogeneous Impacts of Farmer Education on Technology Access and Technical Efficiency in Ghana"

output:
  github_document:
    toc: false
    toc_depth: 3
    
knit: >
  (function(inputFile, encoding) {
    rmarkdown::render(
      inputFile,
      encoding      = encoding,
      output_format = "github_document",
      # always output README.md in the same folder as the .Rmd
      output_file   = paste0(getwd(), "/README.md")
    )
  })
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(collapse = TRUE,comment = "#>",out.width = "100%")
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE,echo = TRUE)
```

For an overview of the broader project context, please refer to the main [GHAgricProductivityLab README](https://github.com/ftsiboe/GHAgricProductivityLab/README.md) in the repository root.

See the [LICENSE](https://github.com/ftsiboe/GHAgricProductivityLab/LICENSE) file in the repository root for details.

**Status**: Currently under review but you can read the working paper [here]().

### Contributers
- [Mark Appiah-Twumasi](https://scholar.google.com/citations?user=SrQaedsAAAAJ&hl=en)
- [Jacob Asravor](https://scholar.google.com/citations?user=_zUi3FsAAAAJ&hl=en)
- [Francis Tsiboe](https://scholar.google.com/citations?user=ox2t_YIAAAAJ&hl=en)

### Abstract


---

*Maintained by [ftsiboe](https://github.com/ftsiboe)*
